name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        A bug is when something works differently than it is expected to.
        ## Remember to search before filing a new report
        Please search for this bug in the issue tracker, and use a bug report title that
        would have made your bug report turn up in the search results for your search query.
  - type: input
    id: version
    attributes:
      label: GGUI Version (Commit)
      description: "The closest GGUI release version and the commit the problem occurs in."
      placeholder: "e.g., 0.1.8.1 (65bf859)"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce and Observed Behavior
      description: What exactly can someone else do, in order to observe the problem that you observed? Include the output and all error messages.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / Output
      description: Include relevant logs (or link to a file) and screenshots if helpful.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        - OS: 
        - Architecture: 
        - Compiler & version: 
        - Build type (Debug/Release): 
        - Terminal / Shell: 
        - Commit / Tag:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the problem in question?
      options:
        - Minor
        - Major
        - Blocking
    validations:
      required: false
  - type: input
    id: related
    attributes:
      label: Related PR or Issue (optional)
      description: List related items, one per line, starting with `- [ ] \#<number>`
      placeholder: "- [ ] #123"
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context here.
